(chore) Security Updates
TUM-Dev/meldeplattform pull request #5
Opened 2024-02-13 14:40 UTC by strobelm

Hey all,

I've prepared a pull request with some security updates for the meldeplattform. Here's a breakdown of the changes:

1. **Run `npm audit fix`**: Ensure that we fix any vulnerabilities reported by npm audit.

2. **Deduplicate version strings in Dockerfile and update to latest versions of Go and Alpine**: Optimize our Dockerfile by removing duplicate version strings and ensuring we're using the latest versions of Go and Alpine.

3. **Update all dependencies recursively**: Ensure we're using the latest security patches and bug fixes by updating all dependencies recursively.

** Impact **

Closes several security vulnerabilities in the go and node packages. No functional changes were done.

** How to test **

I was running this using `podman run --privileged -v ./files:/files -p 8080:8080 `, the page seems to load fine. One thing I noticed using this local setup is that I actually cannot really select an issue. Any input on this?

![image](https://github.com/TUM-Dev/meldeplattform/assets/14185442/264661ae-d8a1-4646-b1df-299ce5defa20)

2024-02-15 19:36 UTC, joschahenningsen commented
> the page seems to load fine. One thing I noticed using this local setup is that I actually cannot really select an issue. Any input on this?

 Can you verify that the config.yaml is mounted next to the executable within the container?  Any reason you use podman over Docker, considering Docker is well maintained and documented for this application?

2024-02-15 19:38 UTC, joschahenningsen requested changes

2024-02-15 19:38 UTC, joschahenningsen commented on go.mod
> +go 1.21
Please use go 1.22

2024-02-15 19:38 UTC, joschahenningsen commented on Dockerfile
> +ARG GOVERSION="1.22"
Don't see a real reason for this but works for me

2024-02-16 11:23 UTC, joschahenningsen commented
> One thing I noticed using this local setup is that I actually cannot really select an issue. Any input on this?

When running this locally, the database will initially be empty and therefore there are no topics to report to. In order to create some you have to log in and create one. This could be a little tricky tho because you don't have the idp certificate locally... Do you want me to build a simple debug mode that allows local admin login in development environments for testing?

2024-02-16 11:23 UTC, joschahenningsen approved these changes

2024-02-16 11:51 UTC, strobelm commented
> > One thing I noticed using this local setup is that I actually cannot really select an issue. Any input on this?
> 
> When running this locally, the database will initially be empty and therefore there are no topics to report to. In order to create some you have to log in and create one. This could be a little tricky tho because you don't have the idp certificate locally... Do you want me to build a simple debug mode that allows local admin login in development environments for testing?

Thanks for the offer, but I think I can manage :slightly_smiling_face:. One more thing I could use your help: I do not have the rights to push the merge button :smile:

2024-02-16 12:32 UTC, merged